version: '3'

services:
  nginx:
    image: arai-nginx
    container_name: nginx
    build:
      context: ./
      dockerfile: ./docker/nginx/dockerfile
    ports:
      - 80:80
    volumes:
      - ./laravel-bbs/public:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    image: arai-php
    container_name: php
    build:
      context: ./
      dockerfile: ./docker/php/dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./laravel-bbs:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
