---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'PHP with SQLite on Elastic Container Service(ECR only)'

Parameters:
  AppEcrRepositoryName:
    Type: String
    Description: ElasticContainerRepository Name
    MinLength: 1
    Default: 'php-app-repo'
  AppEcrRepositoryTag:
    Type: String
    Description: ElasticContainerRepository Tag
    MinLength: 1
    Default: '0.0.1'

Resources:
  # ECR
  PHPElasticContainerRepository:
    Type: 'AWS::ECR::Repository'
    DeletionPolicy: Retain
    Properties:
      RepositoryName: !Sub "${AppEcrRepositoryName}/php"
  NginxElasticContainerRepository:
    Type: 'AWS::ECR::Repository'
    DeletionPolicy: Retain
    Properties:
      RepositoryName: !Sub "${AppEcrRepositoryName}/nginx"
